name: flower_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  provider: ^6.1.1
  shared_preferences: ^2.5.4
  alarm: ^5.2.1
  image_picker: ^1.0.7
  image: ^4.1.3
  google_mlkit_text_recognition: ^0.13.0
  flutter_tesseract_ocr: ^0.4.11
  flutter_blue_plus: ^1.31.0
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  http: ^1.6.0
  flutter_timezone: ^5.0.1
  audioplayers: ^6.0.0    # ← TTS 재생용 추가
  flutter_local_notifications: ^18.0.1
  flutter_foreground_task: ^8.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/blank.mp3
    - assets/tessdata/
    - assets/tessdata/kor.traineddata
    - assets/tessdata/tessdata_config.json